server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6f8ppfgi27c73cp6er0-a.oregon-postgres.render.com:5432/salemanagmentsystem_8dmd?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:12345678901234567890123456789012}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:86400000}

cloudinary.cloud_name=${CLOUD_NAME:dnmk3xqy0}
cloudinary.api_key=${CLOUD_API_KEY:374849278972435}
cloudinary.api_secret=${CLOUD_API_SECRET:k7gRpQkf1Xc87ZQPNhmshB17l6I}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB