server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/salemanagement?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=khanhhy
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB